version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      macvlan0:
        ipv4_address: 192.168.50.253
    environment:
      - CF_API_EMAIL=$EMAIL
      - CF_DNS_API_TOKEN=$APIKEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/username/traefik/data/traefik.yaml:/traefik.yaml:ro
      - /home/username/traefik/data/acme.json:/acme.json
      - /home/username/traefik/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.justAdummyService.loadbalancer.server.port=1337"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.dougjohnson.me`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=$USER:$PASSWORD"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.dougjohnson.me`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=dougjohnson.me"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.dougjohnson.me"
      - "traefik.http.routers.traefik-secure.service=api@internal"